# Generated by Django 4.2.30 on 2026-07-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='show_in_shop',
            field=models.BooleanField(default=True, help_text='Show this painting on the shop page'),
        ),
    ]
